- **Option 1 :** Using 100% of data for train the model and the same data to test the model is not a very good approach.
- **Option 2 :** Split available dataset into training and test sets is a better approach. But if the train and test split is completly different i.e the model has not learned anything related to test data and the prediction can go wrong.
- **Kfold Cross Validation :** We divide the data in folds.
i.e. suppose we have 100 samples we devide it in 5 folds of 20 sample each and we run multiple iteration like first use 1st fold of sample as test and rest 4 folds for training and note the score, then use 2nd fold of sample as test and rest as training samples then note the score, at last use 5th fold ast est and rest as training and again note the score. At last we average out the scores

In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [7]:
# using Logistic Regression
lr = LogisticRegression()
lr.fit(X_train, Y_train)
lr.score(X_test, Y_test)

c:\Users\utkarsh.alpuria\Desktop\My Work\Python\Python ML\Python ML Algorithm\.ml_algo_py_venv\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9537037037037037

In [8]:
# using Support Vector Machine
svm = SVC()
svm.fit(X_train, Y_train)
svm.score(X_test, Y_test)

0.9907407407407407

In [9]:
rf = RandomForestClassifier()
rf.fit(X_train, Y_train)
rf.score(X_test, Y_test)

0.9722222222222222

if you run train_test_split multiple time the score will change for every model

In [10]:
from sklearn.model_selection import KFold
kf = KFold(n_splits = 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [11]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [12]:
def get_score(model, X_train, X_test, Y_train, Y_test):
    model.fit(X_train,Y_train)
    return model.score(X_test, Y_test)

In [29]:
# kFold and StratifiedKFold are same thing
# StratifiedKFold is for suppose different flowers(category) it maintain equilibrium while creating fold so that train and test data have even categories
# from sklearn.model_selection import StratifiedKFold
# folds = StratifiedKFold(n_splits=3) 

kf = KFold(n_splits = 5)
kf

KFold(n_splits=5, random_state=None, shuffle=False)

In [30]:
scores_lr = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):
    X_train, X_test, Y_train, Y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]

    scores_lr.append(get_score(LogisticRegression(), X_train, X_test,  Y_train, Y_test))
    scores_svm.append(get_score(SVC(), X_train, X_test,  Y_train, Y_test))
    scores_rf.append(get_score(RandomForestClassifier(), X_train, X_test,  Y_train, Y_test))

print(scores_lr)
print(scores_svm)
print(scores_rf)

c:\Users\utkarsh.alpuria\Desktop\My Work\Python\Python ML\Python ML Algorithm\.ml_algo_py_venv\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\utkarsh.alpuria\Desktop\My Work\Python\Python ML\Python ML Algorithm\.ml_algo_py_venv\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to t

[0.9277777777777778, 0.8666666666666667, 0.9387186629526463, 0.935933147632312, 0.9080779944289693]
[0.9694444444444444, 0.9472222222222222, 0.9832869080779945, 0.9888579387186629, 0.9415041782729805]
[0.9444444444444444, 0.925, 0.9637883008356546, 0.9749303621169917, 0.935933147632312]


In [31]:
# OR use inbuilt cross val method of sklearn
from sklearn.model_selection import cross_val_score

cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [32]:
# we compared different estimators
# we can also compare same estimator with different parameters, for tuning

cross_val_score(RandomForestClassifier(n_estimators=5), digits.data, digits.target) # 5 trees

array([0.86111111, 0.83055556, 0.8913649 , 0.88300836, 0.82729805])

In [33]:
cross_val_score(RandomForestClassifier(n_estimators=20), digits.data, digits.target) # 20 trees

array([0.91111111, 0.89722222, 0.95821727, 0.95821727, 0.9275766 ])

In [34]:
cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target) # 40 trees

array([0.91944444, 0.91111111, 0.95543175, 0.94986072, 0.91364903])